# _config.yml
author: "redhu"
title: "redhu's blog"
email: "gzhmj@foxmail.com"
description: ""
baseurl: ""
url: "https://redhu.github.io"
destination: ./_site
encoding: UTF-8
paginate: 10 # 每页显示的博文数量
paginate_path: "/posts/page:num" # 分页路径
google_analytics: G-7WY1E9F2CE
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
